[package]
name = "clipboard-aux2"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
arboard = "3.6.1"
aviutl2 = "0.12.2"
chrono = "0.4.43"
dirs = "6.0.0"
image = "0.25.9"
process_path = "0.1.4"
rfd = "0.17.2"
